language: python
sudo: false
python:
  - pypy-5.4.1
  - 2.7
script:
  - python setup.py test
after_success:
  - coveralls
notifications:
  email: false

before_install:
  - python --version

install:
  - pip install -U pip setuptools
  - pip install -U coverage coveralls
  - pip install -U -e .
# cache: pip seems not to work if `install` is replaced (https://github.com/travis-ci/travis-ci/issues/3239)
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.venv

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
